apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: no-critical-cves
spec:
  policyName: No Critical CVEs
  categories:
    - Kubernetes
    - Vulnerability Management
  lifecycleStages:
    - DEPLOY
  eventSource: NOT_APPLICABLE
  scope:
    - cluster: 3985cdcf-74dd-4929-bb48-302ecf99bf05 ## !! Update this to your cluster ID ##
      namespace: demo
  severity: CRITICAL_SEVERITY
  enforcementActions:
    - UNSATISFIABLE_NODE_CONSTRAINT_ENFORCEMENT
  notifiers:
    - stackrox-relay
  policySections:
    - sectionName: Rule 1
      policyGroups:
        - fieldName: Severity
          booleanOperator: OR
          values:
            - value: CRITICAL
            - value: IMPORTANT
        - fieldName: Fixable
          booleanOperator: OR
          values:
            - value: "true"
  criteriaLocked: false
  mitreVectorsLocked: false
  isDefault: false
