apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: no-important-cves
spec:
  policyName: No Important CVEs
  categories:
    - Kubernetes
    - Vulnerability Management
  lifecycleStages:
    - DEPLOY
  eventSource: NOT_APPLICABLE
  scope:
    - cluster: 3985cdcf-74dd-4929-bb48-302ecf99bf05
      namespace: demo
  severity: HIGH_SEVERITY
  notifiers:
    - stackrox-relay
  policySections:
    - sectionName: Rule 1
      policyGroups:
        - fieldName: Severity
          booleanOperator: OR
          values:
            - value: IMPORTANT
        - fieldName: Fixable
          booleanOperator: OR
          values:
            - value: "true"
        - fieldName: Days Since CVE Was First Discovered In Image
          booleanOperator: OR
          values:
            - value: "30"
  criteriaLocked: false
  mitreVectorsLocked: false
  isDefault: false
