apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: no-important-cves
spec:
  policyName: No Important CVEs
  categories:
    - Kubernetes
    - Vulnerability Management
  lifecycleStages:
    - DEPLOY
  eventSource: NOT_APPLICABLE
  scope:
    - cluster: 2801e58e-c366-4c63-be4e-edd5dd9d6084
      namespace: demo
  severity: HIGH_SEVERITY
  notifiers:
    - stackrox-relay
  policySections:
    - sectionName: Rule 1
      policyGroups:
        - fieldName: Severity
          booleanOperator: OR
          values:
            - value: IMPORTANT
        - fieldName: Fixable
          booleanOperator: OR
          values:
            - value: "true"
  criteriaLocked: false
  mitreVectorsLocked: false
  isDefault: false
